# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\user\python_project\dog\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 555)
        font = QtGui.QFont()
        font.setPointSize(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"border-image: url(:/images/main.png);\n"
"}\n"
"#frame * {\n"
"border-image:url();\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, -1, 5, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.max_ = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.max_.setFont(font)
        self.max_.setStyleSheet("QPushButton{background:#F7D674;border-radius:5px;}QPushButton:hover{background:yellow;}")
        self.max_.setText("")
        self.max_.setObjectName("max_")
        self.gridLayout.addWidget(self.max_, 0, 1, 1, 1)
        self.close_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_3.sizePolicy().hasHeightForWidth())
        self.close_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.close_3.setFont(font)
        self.close_3.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}QPushButton:hover{background:red;}")
        self.close_3.setText("")
        self.close_3.setObjectName("close_3")
        self.gridLayout.addWidget(self.close_3, 0, 2, 1, 1)
        self.min_ = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.min_.setFont(font)
        self.min_.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}QPushButton:hover{background:green;}")
        self.min_.setText("")
        self.min_.setObjectName("min_")
        self.gridLayout.addWidget(self.min_, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_24 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_24.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setScaledContents(False)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_6.addWidget(self.label_24)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.dog = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.dog.setFont(font)
        self.dog.setStyleSheet("QPushButton:hover{color:rgb(255,0,0);border-style:inset;}QPushButton{color:rgb(255, 255, 255, 255);border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        self.dog.setObjectName("dog")
        self.verticalLayout.addWidget(self.dog)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.text = QtWidgets.QTextBrowser(self.frame)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setStyleSheet("border-color:white;border:4px;color:white;border-radius:10px;padding:2px 4px;\n"
"background-color:rgb(5, 5, 5)")
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 9)
        self.verticalLayout.setStretch(3, 9)
        self.verticalLayout.setStretch(7, 9)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; color:#ffffff;\">舔狗日记</span></p></body></html>"))
        self.dog.setText(_translate("MainWindow", "开舔"))

import res_rc
